// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: notification.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificationService_ReservationCreated_FullMethodName  = "/pb.NotificationService/ReservationCreated"
	NotificationService_ReservationCanceled_FullMethodName = "/pb.NotificationService/ReservationCanceled"
	NotificationService_HostRated_FullMethodName           = "/pb.NotificationService/HostRated"
	NotificationService_AccommodationRated_FullMethodName  = "/pb.NotificationService/AccommodationRated"
	NotificationService_ReservationResponse_FullMethodName = "/pb.NotificationService/ReservationResponse"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	ReservationCreated(ctx context.Context, in *ReservationNotification, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReservationCanceled(ctx context.Context, in *ReservationNotification, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HostRated(ctx context.Context, in *HostRatingNotification, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AccommodationRated(ctx context.Context, in *AccommodationRatingNotification, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReservationResponse(ctx context.Context, in *ReservationResponseNotification, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) ReservationCreated(ctx context.Context, in *ReservationNotification, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_ReservationCreated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ReservationCanceled(ctx context.Context, in *ReservationNotification, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_ReservationCanceled_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) HostRated(ctx context.Context, in *HostRatingNotification, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_HostRated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) AccommodationRated(ctx context.Context, in *AccommodationRatingNotification, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_AccommodationRated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ReservationResponse(ctx context.Context, in *ReservationResponseNotification, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NotificationService_ReservationResponse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	ReservationCreated(context.Context, *ReservationNotification) (*emptypb.Empty, error)
	ReservationCanceled(context.Context, *ReservationNotification) (*emptypb.Empty, error)
	HostRated(context.Context, *HostRatingNotification) (*emptypb.Empty, error)
	AccommodationRated(context.Context, *AccommodationRatingNotification) (*emptypb.Empty, error)
	ReservationResponse(context.Context, *ReservationResponseNotification) (*emptypb.Empty, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) ReservationCreated(context.Context, *ReservationNotification) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservationCreated not implemented")
}
func (UnimplementedNotificationServiceServer) ReservationCanceled(context.Context, *ReservationNotification) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservationCanceled not implemented")
}
func (UnimplementedNotificationServiceServer) HostRated(context.Context, *HostRatingNotification) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostRated not implemented")
}
func (UnimplementedNotificationServiceServer) AccommodationRated(context.Context, *AccommodationRatingNotification) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccommodationRated not implemented")
}
func (UnimplementedNotificationServiceServer) ReservationResponse(context.Context, *ReservationResponseNotification) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservationResponse not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_ReservationCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ReservationCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ReservationCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ReservationCreated(ctx, req.(*ReservationNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ReservationCanceled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ReservationCanceled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ReservationCanceled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ReservationCanceled(ctx, req.(*ReservationNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_HostRated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRatingNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).HostRated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_HostRated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).HostRated(ctx, req.(*HostRatingNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_AccommodationRated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccommodationRatingNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).AccommodationRated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_AccommodationRated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).AccommodationRated(ctx, req.(*AccommodationRatingNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ReservationResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservationResponseNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ReservationResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ReservationResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ReservationResponse(ctx, req.(*ReservationResponseNotification))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReservationCreated",
			Handler:    _NotificationService_ReservationCreated_Handler,
		},
		{
			MethodName: "ReservationCanceled",
			Handler:    _NotificationService_ReservationCanceled_Handler,
		},
		{
			MethodName: "HostRated",
			Handler:    _NotificationService_HostRated_Handler,
		},
		{
			MethodName: "AccommodationRated",
			Handler:    _NotificationService_AccommodationRated_Handler,
		},
		{
			MethodName: "ReservationResponse",
			Handler:    _NotificationService_ReservationResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
